# Generated by Django 5.2 on 2025-06-03 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Raison sociale')),
                ('siret', models.CharField(max_length=14, unique=True)),
                ('phone', models.CharField(blank=True, max_length=11, verbose_name='Téléphone')),
                ('website', models.URLField(blank=True, verbose_name='Site internet')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email de contact')),
                ('users', models.ManyToManyField(blank=True, related_name='companies', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateurs')),
            ],
            options={
                'verbose_name': 'société',
                'permissions': [('company_update_stock', 'Can update company stocks'), ('company_delete_stock', 'Can delete company stocks'), ('company_add_stock', 'Can add company stocks')],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SH', 'Magasin'), ('WH', 'Entrepôt')], max_length=2)),
                ('name', models.CharField(max_length=100, verbose_name='Raison sociale')),
                ('siret', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('address_line_1', models.CharField(max_length=100, verbose_name='Adresse ligne 1')),
                ('address_line_2', models.CharField(blank=True, max_length=100, verbose_name='Adresse ligne 2')),
                ('zip_code', models.CharField(max_length=10, verbose_name='Code postal')),
                ('city', models.CharField(max_length=30, verbose_name='Ville')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'site',
            },
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('I', 'Entrée'), ('O', 'Sortie'), ('T', 'Transfert')], max_length=1)),
                ('quantity', models.IntegerField(verbose_name='Quantité')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('synced', models.BooleanField(default=False)),
                ('from_location', models.ForeignKey(blank=True, help_text='Nécessaire pour les sorties et transferts', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='inventory.location', verbose_name="Site d'origine")),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.product', verbose_name='Produit')),
                ('to_location', models.ForeignKey(blank=True, help_text='Nécessaire pour les entrées et transferts', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='inventory.location', verbose_name='Site de destination')),
            ],
            options={
                'verbose_name': 'mouvement',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Quantité')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('synch', models.BooleanField(default=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.location', verbose_name='Site')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='Produit')),
            ],
        ),
    ]
