# Generated by Django 5.2 on 2025-06-19 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('I', 'Entrée'), ('O', 'Sortie'), ('T', 'Transfert')], max_length=1)),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantité')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('synced', models.BooleanField(default=False)),
                ('from_location', models.ForeignKey(blank=True, help_text='Nécessaire pour les sorties et transferts', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='management.location', verbose_name="Site d'origine")),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.product', verbose_name='Produit')),
                ('to_location', models.ForeignKey(blank=True, help_text='Nécessaire pour les entrées et transferts', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='management.location', verbose_name='Site de destination')),
            ],
            options={
                'verbose_name': 'mouvement',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantité')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('synch', models.BooleanField(default=True)),
                ('is_low', models.BooleanField(default=False)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.location', verbose_name='Site')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='Produit')),
            ],
        ),
    ]
