# Generated by Django 5.2 on 2025-05-22 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Société'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Site'},
        ),
        migrations.AlterModelOptions(
            name='movement',
            options={'verbose_name': 'Mouvement'},
        ),
        migrations.RemoveField(
            model_name='location',
            name='address',
        ),
        migrations.AddField(
            model_name='location',
            name='address_line_1',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='siret',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='siret',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='type',
            field=models.CharField(choices=[('SH', 'Magasin'), ('WH', 'Entrepôt')], max_length=2),
        ),
        migrations.AlterField(
            model_name='movement',
            name='from_location',
            field=models.ForeignKey(blank=True, help_text='Nécessaire pour les sorties et transferts', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='inventory.location'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='to_location',
            field=models.ForeignKey(blank=True, help_text='Nécessaire pour les entrées et transferts', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='inventory.location'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='type',
            field=models.CharField(choices=[('I', 'Entrée'), ('O', 'Sortie'), ('T', 'Transfert')], max_length=1),
        ),
    ]
