# Generated by Django 5.2 on 2025-06-12 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_company_created_company_last_modified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
    ]
