# Generated by Django 5.2 on 2025-05-24 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_company_options_alter_location_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='synced',
            field=models.BooleanField(default=False),
        ),
    ]
