# Generated by Django 5.2 on 2025-05-25 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_movement_synced'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='synch',
            field=models.BooleanField(default=True),
        ),
    ]
