# Generated by Django 5.2 on 2025-06-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_movement_quantity_alter_stock_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='is_low',
            field=models.BooleanField(default=False),
        ),
    ]
