# Generated by Django 5.2 on 2025-06-18 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_stock_is_low'),
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations = [
                migrations.RemoveField(
                    model_name = 'location',
                    name = 'company',
                ),
            ],
            database_operations = [],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='stock',
                    name='location',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.location', verbose_name='Site'),
                ),
            ],
            # You're reusing an existing table, so do nothing
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='movement',
                    name='to_location',
                    field=models.ForeignKey(blank=True, help_text='Nécessaire pour les entrées et transferts', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='management.location', verbose_name='Site de destination'),
                ),
            ],
            # You're reusing an existing table, so do nothing
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='movement',
                    name='from_location',
                    field=models.ForeignKey(blank=True, help_text='Nécessaire pour les sorties et transferts',
                                            null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+',
                                            to='management.location', verbose_name="Site d'origine"),
                ),
            ],
            # You're reusing an existing table, so do nothing
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='Company',
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name = 'Company',
                    table = 'management_company',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='Location',
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name = 'Location',
                    table = 'management_location',
                ),
            ],
        ),
    ]
