# Generated by Django 5.2 on 2025-05-26 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_category_name_alter_product_categories_and_more'),
        ('inventory', '0004_stock_synch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email de contact'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Raison sociale'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=11, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, verbose_name='Site internet'),
        ),
        migrations.AlterField(
            model_name='location',
            name='address_line_1',
            field=models.CharField(max_length=100, verbose_name='Adresse ligne 1'),
        ),
        migrations.AlterField(
            model_name='location',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Adresse ligne 2'),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(max_length=30, verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='location',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.company', verbose_name='Société'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Raison sociale'),
        ),
        migrations.AlterField(
            model_name='location',
            name='zip_code',
            field=models.CharField(max_length=10, verbose_name='Code postal'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='from_location',
            field=models.ForeignKey(blank=True, help_text='Nécessaire pour les sorties et transferts', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='inventory.location', verbose_name="Site d'origine"),
        ),
        migrations.AlterField(
            model_name='movement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.product', verbose_name='Produit'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='quantity',
            field=models.IntegerField(verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='to_location',
            field=models.ForeignKey(blank=True, help_text='Nécessaire pour les entrées et transferts', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='inventory.location', verbose_name='Site de destination'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.location', verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='Produit'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.IntegerField(verbose_name='Quantité'),
        ),
    ]
