# Generated by Django 5.2 on 2025-05-26 11:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_company_email_alter_company_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'permissions': [('company_update_stock', 'Can update company stocks')], 'verbose_name': 'Société'},
        ),
        migrations.AddField(
            model_name='company',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='companies', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateurs'),
        ),
    ]
