# Generated by Django 5.2 on 2025-05-26 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_company_options_company_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'permissions': [('company_update_stock', 'Can update company stocks')], 'verbose_name': 'société'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'site'},
        ),
        migrations.AlterModelOptions(
            name='movement',
            options={'verbose_name': 'mouvement'},
        ),
    ]
