# Generated by Django 5.2 on 2025-05-29 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_company_options_alter_location_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'permissions': [('company_update_stock', 'Can update company stocks'), ('company_delete_stock', 'Can delete company stocks'), ('company_add_stock', 'Can add company stocks')], 'verbose_name': 'société'},
        ),
    ]
