# Generated by Django 5.2 on 2025-06-30 10:34
from django.contrib.auth.management import create_permissions
from django.db import migrations


def create_default_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")

    # Permissions have to be created before applying them
    for app_config in apps.get_app_configs():
        app_config.models_module = True
        create_permissions(app_config, verbosity=0)
        app_config.models_module = None

    employee_perms = Permission.objects.filter(codename__in=[
        "view_product", "add_product", "change_product", "delete_product",
        "view_stock", "add_stock", "change_stock", "delete_stock",
        "view_movement"
    ])
    employee_group = Group.objects.create(name="employee")
    employee_group.permissions.set(list(employee_perms))

    manager_perms = Permission.objects.filter(codename__in=[
        "view_company", "add_company", "change_company", "delete_company",
        "view_location", "add_location", "change_location", "delete_location",
        "view_user", "add_user", "change_user", "delete_user",
        "view_category", "add_category", "change_category", "delete_category"
    ])
    manager_group = Group.objects.create(name="manager")
    manager_group.permissions.set(list(manager_perms))


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('catalog', '0001_initial'),
        ('inventory', '0001_initial'),
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_groups)
    ]
