# Generated by Django 5.2 on 2025-06-19 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Raison sociale')),
                ('siret', models.CharField(max_length=14, unique=True)),
                ('phone', models.CharField(blank=True, max_length=11, verbose_name='Téléphone')),
                ('website', models.URLField(blank=True, verbose_name='Site internet')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email de contact')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'société',
                'permissions': [('company_update_stock', 'Can update company stocks'), ('company_delete_stock', 'Can delete company stocks'), ('company_add_stock', 'Can add company stocks')],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SH', 'Magasin'), ('WH', 'Entrepôt')], max_length=2)),
                ('name', models.CharField(max_length=100, verbose_name='Raison sociale')),
                ('siret', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('address_line_1', models.CharField(max_length=100, verbose_name='Adresse ligne 1')),
                ('address_line_2', models.CharField(blank=True, max_length=100, verbose_name='Adresse ligne 2')),
                ('zip_code', models.CharField(max_length=10, verbose_name='Code postal')),
                ('city', models.CharField(max_length=30, verbose_name='Ville')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='management.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'site',
            },
        ),
    ]
