# Generated by Django 5.2 on 2025-06-19 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nom de catégorie')),
                ('slug', models.SlugField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'catégorie',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de produit')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='Identifiant')),
                ('price', models.FloatField(default=0, verbose_name='Prix')),
                ('vat', models.FloatField(default=0.2, verbose_name='TVA')),
                ('stock_threshold', models.IntegerField(default=0, verbose_name='Alerte de stock')),
                ('description', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(related_name='products', to='catalog.category', verbose_name='Catégories')),
            ],
            options={
                'verbose_name': 'produit',
            },
        ),
    ]
