# Generated by Django 5.2 on 2025-05-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('vat', models.FloatField()),
                ('stock_threshold', models.IntegerField()),
                ('description', models.TextField()),
                ('categories', models.ManyToManyField(related_name='products', to='catalog.category')),
            ],
        ),
    ]
