# Generated by Django 5.2 on 2025-05-26 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Nom de catégorie'),
        ),
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(related_name='products', to='catalog.category', verbose_name='Catégories'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom de produit'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=50, unique=True, verbose_name='Identifiant'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_threshold',
            field=models.IntegerField(verbose_name='Alerte de stock'),
        ),
        migrations.AlterField(
            model_name='product',
            name='vat',
            field=models.FloatField(default=0.2, verbose_name='TVA'),
        ),
    ]
