# Generated by Django 5.2 on 2025-06-12 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_category_created_category_last_modified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_threshold',
            field=models.IntegerField(default=0, verbose_name='Alerte de stock'),
        ),
    ]
