# Generated by Django 5.2 on 2025-05-26 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_category_name_alter_product_categories_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'catégorie'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'produit'},
        ),
    ]
