name: pystock_staging

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:

env:
  ENV_NAME: Staging
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  DEBUG: ${{ vars.DEBUG }}
  DATABASE_USERNAME: root
  DATABASE_PASSWORD: root
  EMAIL_HOST_USER: ${{ vars.EMAIL_HOST_USER }}
  EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup database
        run: |
          sudo systemctl start mysql.service
          sudo mysql --user=root --password=root
          CREATE DATABASE local_pystock;
          USE local_pystock;
          exit

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run tests with pytest
        run: uv run pytest